name: Github Action pipeline

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html playwright
        playwright install

    - name: Run tests and generate reports
      run: python run_tests.py

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports
